### ISSUE TITLE
Stale/orphaned security group resources

### ISSUE THREAD

**Issue by vikomall** [cloud-ark/cloudark#16]
1. created env
2. deployed app
3. deleted app
4. delete env
5. there is one security group that was created as part of app/env create and it was not deleted

**Comment by devdattakulkarni** [comment]
@vikomall I have added fix for this issue now. Please pull latest master and let me know if it works for you.

**Comment by devdattakulkarni** [comment]
This was fixed in https://github.com/cloud-ark/cloudark/pull/17
