### ISSUE TITLE
Exceptions during env delete

### ISSUE THREAD

**Issue by vikomall** [cloud-ark/cloudark#40]
Noticed couple of exceptions during the env delete;
1)
10/12/2017 06:12:13 PM ()
10/12/2017 06:12:13 PM BEGIN (implicit)
10/12/2017 06:12:13 PM SELECT environment.id AS environment_id, environment.name AS environment_name, environment.status AS environment_status, environment.env_definition AS environment_env_definition, environment.output_config AS environment_output_config, environment.location AS environment_location 
FROM environment
10/12/2017 06:12:13 PM ()
10/12/2017 06:12:44 PM <Received GET request for all environments>: get() server/fmserver.py:292
10/12/2017 06:12:44 PM Exception during reset or similar
Traceback (most recent call last):
  File "/Users/home/repos/cloudark/cloudark-virtenv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 687, in _finalize_fairy
    fairy._reset(pool)
  File "/Users/home/repos/cloudark/cloudark-virtenv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 829, in _reset
    pool._dialect.do_rollback(self)
  File "/Users/home/repos/cloudark/cloudark-virtenv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 440, in do_rollback
    dbapi_connection.rollback()
ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 123145371262976 and this is thread id 140736208827328
10/12/2017 06:12:44 PM Exception closing connection <sqlite3.Connection object at 0x10ed87200>
Traceback (most recent call last):
  File "/Users/home/repos/cloudark/cloudark-virtenv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 300, in _close_connection
    self._dialect.do_close(connection)
  File "/Users/home/repos/cloudark/cloudark-virtenv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 446, in do_close
    dbapi_connection.close()
ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 123145371262976 and this is thread id 140736208827328
10/12/2017 06:12:44 PM SEL

2)
host;x-amz-date
1c77b885006bbadc85766d07e4c7fe2e8a2252e0af725a5f57cbb369faf53da7
10/12/2017 06:14:27 PM StringToSign:
AWS4-HMAC-SHA256
20171012T231427Z
20171012/us-west-2/ec2/aws4_request
5d746d97d3583ade133d7510a960bf7a4fe3d7e69aa737cd5a0da2e00ecdea90
10/12/2017 06:14:27 PM Signature:
21888650985682589029355c05dd735ebf1a3af349a169af33f2df706e4aeecd
10/12/2017 06:14:27 PM Sending http request: <PreparedRequest [POST]>
10/12/2017 06:14:27 PM Resetting dropped connection: ec2.us-west-2.amazonaws.com
10/12/2017 06:14:28 PM "POST / HTTP/1.1" 400 None
10/12/2017 06:14:28 PM Response headers: {'transfer-encoding': 'chunked', 'date': 'Thu, 12 Oct 2017 23:14:27 GMT', 'connection': 'close', 'server': 'AmazonEC2'}
10/12/2017 06:14:28 PM Response body:
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidGroup.NotFound</Code><Message>The security group '01oct1-2017-10-01-12-01-15-http-ssh' does not exist in default VPC 'vpc-72128815'</Message></Error></Errors><RequestID>ba062ffa-0b00-4737-af15-27a56f58e3e1</RequestID></Response>
10/12/2017 06:14:28 PM Event needs-retry.ec2.DeleteSecurityGroup: calling handler <botocore.retryhandler.RetryHandler object at 0x10e93ed10>
10/12/2017 06:14:28 PM No retry needed.
10/12/2017 06:14:28 PM <An error occurred (InvalidGroup.NotFound) when calling the DeleteSecurityGroup operation: The security group '01oct1-2017-10-01-12-01-15-http-ssh' does not exist in default VPC 'vpc-72128815'>: start_thread() server/fmserver.py:41
10/12/2017 06:14:28 PM An error occurred (InvalidGroup.NotFound) when calling the DeleteSecurityGroup operation: The security group '01oct1-2017-10-01-12-01-15-http-ssh' does not exist in default VPC 'vpc-72128815'
Traceback (most recent call last):
  File "server/fmserver.py", line 43, in start_thread
    request_handler_thread.run()
  File "/Users/home/repos/cloudark/server/environment_handler.py", line 102, in run
    self._delete_environment()
  File "/Users/home/repos/cloudark/server/environment_handler.py", line 91, in _delete_environment
    EnvironmentHandler.registered_cloud_handlers['aws'].delete_cluster(self.env_id, self.environment_info, resource)
  File "/Users/home/repos/cloudark/server/aws_handler.py", line 79, in delete_cluster
    ext.obj.delete_cluster(env_id, env_info, resource)
  File "/Users/home/repos/cloudark/server/server_plugins/aws/coe/ecs.py", line 367, in delete_cluster
    ECSHandler.awshelper.delete_security_group_for_vpc(vpc_id, sec_group_id, sec_group_name)
  File "/Users/home/repos/cloudark/server/server_plugins/aws/aws_helper.py", line 130, in delete_security_group_for_vpc
    self.ec2_client.delete_security_group(GroupId=group_id, GroupName=group_name)
  File "/Users/home/repos/cloudark/cloudark-virtenv/lib/python2.7/site-packages/botocore/client.py", line 312, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/home/repos/cloudark/cloudark-virtenv/lib/python2.7/site-packages/botocore/client.py", line 601, in _make_api_call
    raise error_class(parsed_response, operation_name)
ClientError: An error occurred (InvalidGroup.NotFound) when calling the DeleteSecurityGroup operation: The security group '01oct1-2017-10-01-12-01-15-http-ssh' does not exist in default VPC 'vpc-72128815'
10/12/2017 06:16:28 PM <Received GET request for all environments>: get() server/fmserver.py:292
10/12/2017 06:16:28 PM SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
10/12/2017 06:16:28 PM ()
10/12/2017 06:16:28 PM SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
10/12/2017 06:16:28 PM ()
10/12/2017 06:16:28 PM BEGIN (implicit)
10/12/2017 06:16:28 PM SELECT environment.id AS environment_id, environment.name AS environment_name, environment.status AS environment_status, environment.env_definition AS environment_env_definition, environment.output_config AS environment_output_config, environment.location AS environment_location 
FROM environment
10/12/2017 06:16:28 PM ()

**Comment by devdattakulkarni** [comment]
Thanks @vikomall 

I have now added exception handling for all aws calls. This way situations like above will not prevent subsequent steps from proceeding.

**Comment by devdattakulkarni** [comment]
Haven't encountered this issue in recent testing, so closing it.
