### ISSUE TITLE
env create is failing

### ISSUE THREAD

**Issue by vikomall** [cloud-ark/cloudark#7]
I am following instructions given at https://github.com/cloud-ark/cloudark-samples/tree/master/wordpress and ran into following issue.
**cld env create staging environment-rds-ecs.yaml**
Something caused error in cloudark. Please submit bug report on cloudark github repo. Attach logs from cld.log which is available in cloudark directory.
local variable 'response' referenced before assignment

following is from cld.log
09/19/2017 09:51:22 PM <Received GET request for all environments>: get() server/fmserver.py:340
09/19/2017 09:54:22 PM <Received GET request for all apps>: get() server/fmserver.py:208
09/19/2017 10:04:31 PM <Received GET request for all environments>: get() server/fmserver.py:340
09/19/2017 10:04:42 PM <Received POST request to deploy app>: post() server/fmserver.py:147
09/19/2017 10:05:01 PM <Received GET request for all environments>: get() server/fmserver.py:340
09/19/2017 10:05:14 PM <Received DELETE request for environment 1>: delete() server/fmserver.py:371
09/19/2017 10:05:30 PM <Received GET request for all apps>: get() server/fmserver.py:208
09/19/2017 10:07:45 PM <Received GET request for all apps>: get() server/fmserver.py:208
09/19/2017 10:07:50 PM <Received DELETE request for app 1>: delete() server/fmserver.py:282
09/19/2017 10:07:54 PM <Received GET request for all apps>: get() server/fmserver.py:208
09/19/2017 10:11:53 PM <Received GET request for all apps>: get() server/fmserver.py:208
09/19/2017 10:11:57 PM <Received DELETE request for app 1>: delete() server/fmserver.py:282
09/19/2017 10:20:05 PM <Received POST request to create environment>: post() server/fmserver.py:305

**Comment by devdattakulkarni** [comment]
Thanks for the bug report @vikomall.

Can you add the git commit sha of cloudark that you are working with?

**Comment by vikomall** [comment]
@devdattakulkarni 
cloudark-samples# ee485ba
cloudark# fb93890
Let me know if you need any other info.,

**Comment by devdattakulkarni** [comment]
@vikomall Is this issue still valid? I have not experienced it.

**Comment by devdattakulkarni** [comment]
This issue has not been encountered in recent testing so closing it.
